### ISSUE TITLE
Boommenu open at startup

### ISSUE THREAD

**Issue by dariolr** [Nightonke/VHBoomMenuButton#1]
Great work, thank you!

how can I do to boom at startup?

i mean call boom() method on viewDidLoad. Any help?

**Comment by Nightonke** [comment]
Hey! You can use `autoBoom` or `autoBoomImmediately` properties to boom at startup from version 2.0.0. Check [Control BMB](https://github.com/Nightonke/VHBoomMenuButton/wiki/Control-BMB-(Swift)) for details.

**Comment by dariolr** [comment]
Thank you so much
