### ISSUE TITLE
Dragable Button can't boom

### ISSUE THREAD

**Issue by AlasKuNull** [Nightonke/VHBoomMenuButton#14]
When dragable is YES , button can't boom.

**Comment by jalakoo** [comment]
A user has to tap very quickly or dead straight up & down to kick off the boom before the drag handling begins.  I think all of the BoomMenuButton's touch handling actions need to be replaced with gesture recognizers to handle this better.

**Comment by AlasKuNull** [comment]
Thanks for reply.
